name: MSIX Wrapper
description: Package wrapper using .Net Framework
author: frg2089
inputs:
  msix:
    description: Path to MSIX package
    required: true
  name:
    description: Assembly name
    default: MsixInstaller
  arch:
    description: Package architecture (neutral|x86|x64|arm|arm64)
    required: false
  version:
    description: Package version
    required: false

outputs:
  path:
    description: Installer Path
    value: ${{ steps.Pack-MsixInstaller.outputs.path }}
  algorithm:
    description: Installer Checksum Algorithm
    value: ${{ steps.Pack-MsixInstaller.outputs.algorithm }}
  checksum:
    description: Installer Checksum Value
    value: ${{ steps.Pack-MsixInstaller.outputs.checksum }}

runs:
  using: composite
  steps:
    - uses: actions/setup-dotnet@v5

    - id: Pack-MsixInstaller
      shell: pwsh
      env: 
        MSIX_Version: ${{ inputs.version }}
        MSIX_Arch: ${{ inputs.arch }}
      run: . '${{ github.action_path }}\scripts\Pack-MsixInstaller.ps1' -Path '${{ inputs.msix }}' -Name '${{ inputs.name }}'
